version: '3.9'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.32
    container_name: "course"
    volumes:
      - mysql-course:/var/lib/mysql
      - "./images/mysql/init:/docker-entrypoint-initdb.d"
      - "./images/mysql/configuration:/etc/mysql/conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - '3379'
volumes:
  mysql-course:
    driver: local